[{"id":1080679891,"node_id":"R_kgDOQGnd0w","name":"CVE-2025-8088","full_name":"kaucent/CVE-2025-8088","private":false,"owner":{"login":"kaucent","id":105523209,"node_id":"U_kgDOBkooCQ","avatar_url":"https://avatars.githubusercontent.com/u/105523209?v=4","url":"https://api.github.com/users/kaucent","html_url":"https://github.com/kaucent","type":"User","site_admin":false},"html_url":"https://github.com/kaucent/CVE-2025-8088","description":"Path traversal tool based on cve-2025-8088 vulnerability","fork":false,"url":"https://api.github.com/repos/kaucent/CVE-2025-8088","created_at":"2025-10-21T17:59:28Z","updated_at":"2025-10-21T18:01:50Z","pushed_at":"2025-10-21T18:01:36Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":["cve-2025-8088"],"visibility":"public","forks":0,"watchers":0,"default_branch":"main","score":1},{"id":120799852,"node_id":"MDEwOlJlcG9zaXRvcnkxMjA3OTk4NTI=","name":"CVE-2017-7679-in-python","full_name":"snknritr/CVE-2017-7679-in-python","private":false,"owner":{"login":"snknritr","id":36276619,"node_id":"MDQ6VXNlcjM2Mjc2NjE5","avatar_url":"https://avatars.githubusercontent.com/u/36276619?v=4","url":"https://api.github.com/users/snknritr","html_url":"https://github.com/snknritr","type":"User","site_admin":false},"html_url":"https://github.com/snknritr/CVE-2017-7679-in-python","description":"At this project, we made a python exploit using buffer overflow at the CVE-2017-7679","fork":false,"url":"https://api.github.com/repos/snknritr/CVE-2017-7679-in-python","created_at":"2018-02-08T18:21:18Z","updated_at":"2024-08-12T19:36:08Z","pushed_at":"2018-02-08T18:21:19Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"master","score":1}]